### ISSUE TITLE
Einzug im Backend

### ISSUE THREAD

**Issue by akroii** [numero2/contao-mobile-only#2]
Die Erweiterung verursacht im Contao Backend (Seitenbaum) einen Einzug, wodurch jede verschachtelte Seite scheinbar nicht eingezogen wurde. Dadruch entsteht der Eindruck, dass eine Seite nicht verschachtelt wurde.

Ohne Erweiterung mobile-only:
![bildschirmfoto 2018-02-08 um 14 28 57](https://user-images.githubusercontent.com/8830861/35977983-c4f326aa-0ce4-11e8-9bc1-37bb1ccb3333.png)

Falsche Darstellung mit mobile-only:
![bildschirmfoto 2018-02-08 um 15 23 42](https://user-images.githubusercontent.com/8830861/35977820-5b86df54-0ce4-11e8-96af-e124b611df1b.png)

Mit geöffneter dev-bar. Keine Unterschiede im CSS.
![bildschirmfoto 2018-02-08 um 15 27 10](https://user-images.githubusercontent.com/8830861/35977916-9537ca24-0ce4-11e8-90b8-380a4a39dbf7.png)

Ich benutze Contao 4.4.13 mit mobile-only v1.0.2.
Sobald ich die Erweiterung deinstalliere ist alles wieder in Ordnung.

**Comment by bennyborn** [comment]
Danke für die Info, habe gerade einen Hotfix v1.0.3 rausgehauen damit passt es wieder!
